revoke:
  rules:
  - changes:
    - apps/revokeTmp
  script:
  - echo "revoke"
  - docker
  - docker stop 983fd0a5971e
  - docker rm 983fd0a5971e
  - python C:\Users\user\rams\projcet\apps\updateDeployment.py -m 0 -a "revoking"
  stage: revoke
  tags:
  - AILab
stages:
- revoke
