stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - "local-use"
  only:
    - master
  script:
    - echo "build"

test:
  stage: test
  tags:
    - "local-use"
  only:
    - master
  script:
    - echo "testing"

deploy:
  stage: deploy
  tags:
    - "local-use"
  only:
    - master
  script:
    - echo "deploy"
  rules:
    - changes: 
      - model_registry/**/*



