build:
  only:
  - scenario_2
  script:
  - echo "build"
  stage: build
  tags:
  - AILab
deploy:
  after_script:
  - python updateDeploymentCsv.py -m 0
  rules:
  - changes:
    - ASLFN/docker_apps/*
  script:
  - echo "deploy"
  - docker
  - cd ASLFN
  - docker build -t aslfn:latest -f rootuser.Dockerfile .
  - docker run -p 8685:8002 -d aslfn:latest
  - cd C:\Users\user\rams\projcet\apps
  - docker ps -l | findstr aslfn > dockerTmp
  stage: deploy
  tags:
  - AILab
stages:
- build
- test
- deploy
test:
  only:
  - scenario_2
  script:
  - echo "testing"
  stage: test
  tags:
  - AILab
