deploy:
  rules:
  - changes:
    - developer_upload/timeTmp
  script:
  - echo "deploy"
  - docker
  - cd developer_upload\cramming-kang
  - tar -xf cramming-kang.zip
  - docker build -t cramming-kang:latest -f rootuser.Dockerfile .
  - 'docker run --name cramming-kang -p 8810:8005 -d cramming-kang:latest '
  stage: deploy
  tags:
  - AILab
stages:
- deploy
