revoke:
  rules:
  - changes:
    - apps/revokeTmp
  script:
  - echo "revoke"
  - docker
  - docker stop 8261f49ba3a3
  - docker rm 8261f49ba3a3
  - python C:\Users\user\rams\projcet\apps\updateDeployment.py -m 4 -a "revoking"
  stage: revoke
  tags:
  - AILab
stages:
- revoke
