deploy:
  rules:
  - changes:
    - developer_upload/timeTmp
  script:
  - echo "deploy"
  - docker
  - cd developer_upload\reorganizing-dorothy
  - tar -xf reorganizing-dorothy.zip
  - docker build -t reorganizing-dorothy:latest -f rootuser.Dockerfile .
  - 'docker run --name reorganizing-dorothy -p 8089:8005 -d reorganizing-dorothy:latest '
  stage: deploy
  tags:
  - AILab
stages:
- deploy
