deploy:
  rules:
  - changes:
    - developer_upload/timeTmp
  script:
  - echo "deploy"
  - docker
  - cd developer_upload\reorganizing-susan
  - tar -xf reorganizing-susan.zip
  - docker build -t reorganizing-susan:latest -f rootuser.Dockerfile .
  - 'docker run --name reorganizing-susan -p 8079:8005 -d reorganizing-susan:latest '
  stage: deploy
  tags:
  - AILab
stages:
- deploy
