stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - "AILab"
  only:
    - scenario_2
  script:
    - echo "build"

test:
  stage: test
  tags:
    - "AILab"
  only:
    - scenario_2
  script:
    - echo "testing"

deploy:
  stage: deploy
  tags:
    - "AILab"
  script:
    - echo "deploy"
    - docker
    - cd ASLFN
    - docker build -t aslfn:latest -f rootuser.Dockerfile .
    - docker run -p 8002:8002 -d aslfn:latest
  rules:
    - changes:
      - ASLFN/*

