stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - "local-use"
  script:
    - echo "build"

test:
  stage: test
  tags:
    - "local-use"
  script:
    - echo "testing"

deploy:
  stage: deploy
  tags:
    - "local-use"
  script:
    - echo "deploy"
  rules:
    - changes: 
      - model_registry/*
  when: always



