build:
  only:
  - scenario_2
  script:
  - echo "build"
  stage: build
  tags:
  - AILab
revoke:
  rules:
  - changes:
    - apps/revokeTmp
  script:
  - echo "revoke"
  - docker
  - docker stop bec2e259417e
  - docker rm bec2e259417e
  - python C:\Users\user\rams\projcet\apps\updateDeploymentCsv.py -m 2 -a "revoking"
  stage: revoke
  tags:
  - AILab
stages:
- build
- test
- revoke
test:
  only:
  - scenario_2
  script:
  - echo "testing"
  stage: test
  tags:
  - AILab
