stages:
- train
train:
  rules:
  - changes:
    - developer_upload/timeTmp
  script:
  - echo "train"
  - cd developer_upload\hw1-110356004
  - tar -xf hw1-110356004.zip
  - python hw1.py
  stage: train
  tags:
  - AILab
