revoke:
  rules:
  - changes:
    - apps/revokeTmp
  script:
  - echo "revoke"
  - docker
  - docker stop None
  - docker rm None
  - python C:\Users\user\rams\projcet\apps\updateDeployment.py -m 2 -a "revoking"
  stage: revoke
  tags:
  - AILab
stages:
- revoke
