stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - "AILab"
  only:
    - scenario_2
  script:
    - echo "build"

test:
  stage: test
  tags:
    - "AILab"
  only:
    - scenario_2
  script:
    - echo "testing"

deploy:
  stage: deploy
  tags:
    - "AILab"
  script:
    - echo "deploy"
  rules:
    - changes:
      - model_registry/*

