revoke:
  rules:
  - changes:
    - apps/revokeTmp
  script:
  - echo "revoke"
  - docker
  - docker stop 1f51ae2b2a22
  - docker rm 1f51ae2b2a22
  - python C:\Users\user\rams\projcet\apps\updateDeployment.py -m 18 -a "revoking"
  stage: revoke
  tags:
  - AILab
stages:
- revoke
