deploy:
  rules:
  - changes:
    - developer_upload/timeTmp
  script:
  - echo "deploy"
  - docker
  - cd developer_upload\cramming-howard
  - tar -xf cramming-howard.zip
  - docker build -t cramming-howard:latest -f rootuser.Dockerfile .
  - 'docker run --name cramming-howard -p 8584:8005 -d cramming-howard:latest '
  stage: deploy
  tags:
  - AILab
stages:
- deploy
