deploy:
  rules:
  - changes:
    - developer_upload/timeTmp
  script:
  - echo "deploy"
  - docker
  - cd developer_upload\reorganizing-louis
  - tar -xf reorganizing-louis.zip
  - docker build -t reorganizing-louis:latest -f rootuser.Dockerfile .
  - 'docker run --name reorganizing-louis -p 8623:8005 -d reorganizing-louis:latest '
  stage: deploy
  tags:
  - AILab
stages:
- deploy
