deploy:
  rules:
  - changes:
    - developer_upload/timeTmp
  script:
  - echo "deploy"
  - docker
  - cd developer_upload\matching-yetta
  - tar -xf matching-yetta.zip
  - docker build -t matching-yetta:latest -f rootuser.Dockerfile .
  - 'docker run --name matching-yetta -p 8303:8005 -d matching-yetta:latest '
  stage: deploy
  tags:
  - AILab
stages:
- deploy
