revoke:
  rules:
  - changes:
    - apps/revokeTmp
  script:
  - echo "revoke"
  - docker
  - docker stop 56cf9c7f5776
  - docker rm 56cf9c7f5776
  - python C:\Users\user\rams\projcet\apps\updateDeployment.py -m 6 -a "revoking"
  stage: revoke
  tags:
  - AILab
stages:
- revoke
