deploy:
  rules:
  - changes:
    - developer_upload/timeTmp
  script:
  - echo "deploy"
  - docker
  - cd developer_upload\matching-iverson
  - tar -xf matching-iverson.zip
  - docker build -t matching-iverson:latest -f rootuser.Dockerfile .
  - 'docker run --name matching-iverson -p 8110:8005 -d matching-iverson:latest '
  stage: deploy
  tags:
  - AILab
stages:
- deploy
