build:
  only:
  - scenario_2
  script:
  - echo "build"
  stage: build
  tags:
  - AILab
revoke:
  rules:
  - changes:
    - apps/revokeTmp
  script:
  - echo "revoke"
  - docker
  - docker stop 6203d61d627c
  - docker rm 6203d61d627c
  - python C:\Users\user\rams\projcet\apps\updateDeployment.py -m 1 -a "revoking"
  stage: revoke
  tags:
  - AILab
stages:
- build
- test
- revoke
test:
  only:
  - scenario_2
  script:
  - echo "testing"
  stage: test
  tags:
  - AILab
