deploy:
  rules:
  - changes:
    - developer_upload/timeTmp
  script:
  - echo "deploy"
  - docker
  - cd developer_upload\matching-zoe
  - tar -xf matching-zoe.zip
  - docker build -t matching-zoe:latest -f rootuser.Dockerfile .
  - 'docker run --name matching-zoe -p 8546:8005 -d matching-zoe:latest '
  stage: deploy
  tags:
  - AILab
stages:
- deploy
