revoke:
  rules:
  - changes:
    - apps/revokeTmp
  script:
  - echo "revoke"
  - docker
  - docker stop 453405b5c7ac
  - docker rm 453405b5c7ac
  - python C:\Users\user\rams\projcet\apps\updateDeployment.py -m 0 -a "revoking"
  stage: revoke
  tags:
  - AILab
stages:
- revoke
