revoke:
  rules:
  - changes:
    - apps/revokeTmp
  script:
  - echo "revoke"
  - docker
  - docker stop None
  - docker rm None
  - python C:\Users\ASUS\Desktop\NCCU\Thesis\first-try\apps\updateDeployment.py -m
    0 -a "revoking"
  stage: revoke
  tags:
  - laptop-ASUS
stages:
- revoke
