deploy:
  rules:
  - changes:
    - developer_upload/timeTmp
  script:
  - echo "deploy"
  - docker
  - cd developer_upload\cramming-julian
  - tar -xf cramming-julian.zip
  - docker build -t cramming-julian:latest -f rootuser.Dockerfile .
  - 'docker run --name cramming-julian -p 8696:8005 -d cramming-julian:latest '
  stage: deploy
  tags:
  - AILab
stages:
- deploy
