revoke:
  rules:
  - changes:
    - apps/revokeTmp
  script:
  - echo "revoke"
  - docker
  - docker stop 80ab1aff4722
  - docker rm 80ab1aff4722
  - python C:\Users\user\rams\projcet\apps\updateDeployment.py -m 1 -a "revoking"
  stage: revoke
  tags:
  - AILab
stages:
- revoke
