stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - "AILab"
  only:
    - master
  script:
    - echo "build"
  rules:
    - changes: 
      - model_registry/*

test:
  stage: test
  tags:
    - "AILab"
  script:
    - echo "testing"
  rules:
    - changes: 
      - model_registry/*

deploy:
  stage: deploy
  tags:
    - "AILab"
  only:
    - master
  script:
    - echo "deploy"
  rules:
    - changes: 
      - model_registry/*
  when: always



