deploy:
  rules:
  - changes:
    - developer_upload
  script:
  - echo "deploy"
  - docker
  - cd developer_upload
  - tar -xf {module_name}.zip
  - cd {module_name}
  - docker build -t {module_name}:latest -f rootuser.Dockerfile .
  - docker run -p 8159:8005 -d testing-yetta:latest
  stage: deploy
  tags:
  - laptop-ASUS
stages:
- deploy
