revoke:
  rules:
  - changes:
    - apps/revokeTmp
  script:
  - echo "revoke"
  - docker
  - docker stop 4878829ffef6
  - docker rm 4878829ffef6
  - python C:\Users\user\rams\projcet\apps\updateDeployment.py -m 7 -a "revoking"
  stage: revoke
  tags:
  - AILab
stages:
- revoke
