deploy:
  rules:
  - changes:
    - developer_upload/timeTmp
  script:
  - echo "deploy"
  - docker
  - cd developer_upload\cramming-leo
  - tar -xf cramming-leo.zip
  - docker build -t cramming-leo:latest -f rootuser.Dockerfile .
  - 'docker run --name cramming-leo -p 8147:8005 -d cramming-leo:latest '
  stage: deploy
  tags:
  - AILab
stages:
- deploy
