deploy:
  rules:
  - changes:
    - developer_upload/timeTmp
  script:
  - echo "deploy"
  - docker
  - cd developer_upload\matching-yetta
  - tar -xf matching-yetta.zip
  - cd matching-yetta
  - docker build -t matching-yetta:latest -f rootuser.Dockerfile .
  - docker run -p 8915:8005 -d matching-yetta:latest
  stage: deploy
  tags:
  - AILab
stages:
- deploy
