---
version: '2'
services:
    nginx : 
      image : 110356021/nginx-server:latest
      hostname: nginx
      container_name: nginx
      ports : 
        - "80:80"

    mongo : 
      image : mongo:latest
      hostname: mongo
      container_name: mongo
      ports : 
        - "27017:27017"
      volumes:
        - mongodbdata:/data/db
        - ./mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      command: [--auth]
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootPassword
        MONGO_INITDB_DATABASE: model

    mongodb-python-api : 
      image : 110356021/mongodb-python-api:latest
      hostname: mongodb-python-api
      container_name: mongodb-python-api
      ports : 
        - "8001:8001"
volumes:
  mongodbdata:
    external: true
